services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: ./.env
    networks:
      - backend
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: { }
networks:
  backend: { }
