services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: ./.env
    networks:
      - backend
    volumes:
      - postgresql:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    env_file: ./.env
    command:
      - --changelog-file=db.master-changelog.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    networks:
      - backend
    volumes:
      - ./db/migrations:/liquibase/changelog

#  back:
#    image: vladis7love/cookainno_back:latest
#    depends_on:
#      - liquibase
#    ports:
#      - "8080:8080"
#    env_file: ./.env
#    networks:
#      - backend
#    tty: true
#
#  ml:
#    image: vladis7love/cookainno_ml:latest
#    depends_on:
#      - liquibase
#    ports:
#      - "8000:8000"
#    networks:
#      - backend
#    tty: true

volumes:
  postgresql: { }
networks:
  backend: { }
