package com.cookainno.mobile.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF434657)//topbar
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF393B47)//knopk
val onPrimaryContainerLight = Color(0xFFB3B1B0)
val secondaryLight = Color(0xFF2C1B20)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8F547)
val onSecondaryContainerLight = Color(0xFF4B5100)
val tertiaryLight = Color(0xFF7D3650)
val onTertiaryLight = Color(0xFFFFFFFF)
//val tertiaryContainerLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA85974)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
//val errorContainerLight = Color(0xFFFFDAD6)
val errorContainerLight = Color(0xFFFFFFFF)
val onErrorContainerLight = Color(0xFF410002)
//val backgroundLight = Color(0xFF707FA6) //fon
val backgroundLight = Color(0xFFB4C1E2)
//val onBackgroundLight = Color(0xFF5B1839)
val onBackgroundLight = Color(0xFF5C6076) //navigator
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF27171C)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)//text
val inverseSurfaceLight = Color(0xFF000000)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)//umolchanie
val inversePrimaryLight = Color(0xFFC8C6C5)
//
//val surfaceDimLight = Color(0xFFF1D2DA)
val surfaceDimLight = Color(0xFFFFFFFF)
val surfaceBrightLight = Color(0xFFD3D3D3)//fonfon
val surfaceContainerLowestLight = Color(0xFFFFFFFF)//kartochki
val surfaceContainerLowLight = Color(0xFFFFFFFF)
val surfaceContainerLight = Color(0xFFFFFFFF)
val surfaceContainerHighLight = Color(0xFF314371)//links
val surfaceContainerHighestLight = Color(0xFFFFFFFF)



val primaryDark = Color(0xFF242731)//topbar
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF0D0D0D)
val onPrimaryContainerDark = Color(0xFF000000) //knopk
val secondaryDark = Color(0xFFCDDA1A)
val onSecondaryDark = Color(0xFF2F3300)
val secondaryContainerDark = Color(0xFFD1DE2F)
val onSecondaryContainerDark = Color(0xFFBFC761)
val tertiaryDark = Color(0xFFD81B60)
val onTertiaryDark = Color(0xFFB4C1E2)
val tertiaryContainerDark = Color(0xFF3949AB)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFF5E0A00)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF5E35B1)
val onErrorContainerDark = Color(0xFF00897B)
val backgroundDark = Color(0xFF495881) //fon
val onBackgroundDark = Color(0xFF3B4050)//navig
val surfaceDark = Color(0xFF000000)
val onSurfaceDark = Color(0xFF000000)//text v textfieldax
val surfaceVariantDark = Color(0xFF8E24AA)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFFFFFFFF)
val scrimDark = Color(0xFFFFFFFF) //text
val inverseSurfaceDark = Color(0xFF43A047)
val inverseOnSurfaceDark = Color(0xFFFFFFFF)
val inversePrimaryDark = Color(0xFF000000)//text on search
val surfaceDimDark = Color(0xFFFFFFFF)
val surfaceBrightDark = Color(0xFF3D446D)
val surfaceContainerLowestDark = Color(0xFF0D0F14) //cartocki
val surfaceContainerLowDark = Color(0xFFFFFFFF) //kogda otkr kameru
val surfaceContainerDark = Color(0xFF43A047)
val surfaceContainerHighDark = Color(0xFF8C9CFF)
val surfaceContainerHighestDark = Color(0xFFF4511E)